### PR TITLE
Resolve potential OneOf naming collisions

### LINKED ISSUE #51: Oneof convert-* field name collision
In 0.9.3 if two messages (A and B) have oneof fields with the same name (in this case: my_oneof), the generated code contains a single convert-my-oneof function for message: A but no convert-* function for message: B. 

new-B calls A's convert-my-oneof function resulting in a B-record instance with missing fields.

```
syntax = "proto3";
package com.example.ab;

message A {
  oneof my_oneof {
    string s = 1;
    int32 i = 2;
  };
}

message B {
  oneof my_oneof {
    bool b = 1;
    float f = 2;
  };
}
```

Produces:
```
(defn convert-my-oneof [origkeyval]
  (cond
     (get-in origkeyval [:my-oneof :s]) origkeyval
     (get-in origkeyval [:my-oneof :i]) origkeyval
     :default origkeyval))

(defn new-A
  "Creates a new instance from a map, similar to map->A except that
  it properly accounts for nested messages, when applicable.
  "
  [init]
  {:pre [(if (s/valid? ::A-spec init) true (throw (ex-info "Invalid input" (s/explain-data ::A-spec init))))]}
  (-> (merge A-defaults init)
      (convert-my-oneof)
      (map->A-record)))

(defn new-B
  "Creates a new instance from a map, similar to map->B except that
  it properly accounts for nested messages, when applicable.
  "
  [init]
  {:pre [(if (s/valid? ::B-spec init) true (throw (ex-info "Invalid input" (s/explain-data ::B-spec init))))]}
  (-> (merge B-defaults init)
      (convert-my-oneof)
      (map->B-record)))
```

### PR DESCRIPTION
**Pull request by sharrap**
Resolves #51 by prepending the message name to all methods generated to handle `oneof` fields, and updates the tests to reflect the new format. For instance,

```proto
message Foo {
  oneof bar { ... }
}
```

Will generate methods named `*-Foo-bar-*` rather than `*-bar-*`.

---

Also bumps `com.google.protobuf/protobuf-java` since leiningen wasn't happy with the old version for me.

RE the DCO, I wasn't sure whether you want a full DCO copied into each commit or just the one-line signoff similar to your commit messages elsewhere in this repo. Let me know if you'd like me to change it. Thanks!

### CODE REVIEW

**Comment by ghaskins** [comment]
Thanks Sean, this is great.  All we need is a signed-off-by, and you passed the DCO-bot so all good there.  I took a quick look at the patch and do not see any issues.  I will pull this down and test it, but assuming that looks good I think this can go in.

Thanks again.

**Comment by sharrap** [comment]
Found a bug, not ready to merge yet.

**Comment by sharrap** [comment]
Okay, should work now as I can tell with some simple tests + reading of the generated source. Unfortunately the new change had to be considerably more involved.

**Comment by ghaskins** [comment]
@sharrap sorry for the delay.  Patch looks good.  Please add yourself to the [CONTRIBUTORS](https://github.com/protojure/protoc-plugin/blob/master/CONTRIBUTORS.md) file, and this can go in.

**Comment by sharrap** [comment]
Sounds good: added a commit and merged master, should be good. Thanks!

**Comment by sharrap** [comment]
Whoops, misclick.

**Review by ghaskins — COMMENTED** [review]
LGTM, thank you!

**Review by ghaskins — APPROVED** [review]

**Pull request merged**
